inc =  -lm 

all:  prob0.cpp
	g++ -w -o prob0 prob0.cpp -Wno-deprecated -I ${inc} 

prob0: prob0.cpp
	g++ -w -o prob0 prob0.cpp -Wno-deprecated -I ${inc}
 
prob1: prob1.cpp
	g++ -w -o prob1 prob1.cpp -Wno-deprecated -I ${inc}

prob2: prob2.cpp
	g++ -w -o prob2 prob2.cpp -Wno-deprecated -I ${inc}

prob3: prob3.cpp
	g++ -w -o prob3 prob3.cpp -Wno-deprecated -I ${inc}

prob4: prob4.cpp
	g++ -w -o prob4 prob4.cpp -Wno-deprecated -I ${inc}

clean:
	rm -f prob0 prob1 prob2 prob3 prob4